### ISSUE TITLE
Please implement "server.listen() also accepts a udp socket"

### ISSUE THREAD

**Issue by RainaBatwing** [mafintosh/utp#5]
I would like to use µTP on top of protocols other than UDP. The readme suggests this is possible but index.js looks hardcoded to use node's dgram library.

My specific application is to wrap the UDP messages in encrypted containers and use an abstract address with the lower level tracking IP changes, so users can move between wifi and cellular.

It would also be useful if the dgram socket interface could trigger µTP to restart to slowstart again, when the underlying network changes to another address or medium. Could µTP listen to an event on the socket for this? something like "reset", causing all the congestion control logic to reset to a default state as if the connection has just been newly opened?

**Comment by mafintosh** [comment]
You can now pass a udp socket to server.listen in 0.0.8

**Comment by mafintosh** [comment]
Send me a PR for the reset thing :)

**Comment by RainaBatwing** [comment]
Could the same logic also be pasted in to exports.connect() so a socket can be passed in for this also?

**Comment by RainaBatwing** [comment]
Also thank you for such a quick update! I will definitely implement the "reset" feature when I have time. I'm currently quite busy with some other urgent projects.
